webtalk_init -webtalk_dir C:\\Users\\Wangsir\\Documents\\SOC\\xup\\lab6SoC\\lab6SoC.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期三 三月 22 11:18:52 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211278044_0_0_104" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "il5cdv2h932615ob9gfuio9f7v" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1512 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_add_data -client project -key date_generated -value "星期三 三月 22 11:17:34 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211278044_0_0_104" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "troa3kmi6kq53ueab1913nq6g" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1512 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1490148111851" -context "sdk\\\\bsp/1490148111851"
webtalk_add_data -client sdk -key hwid -value "1489991901929" -context "sdk\\\\bsp/1490148111851"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1490148111851"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1490148111851"
webtalk_add_data -client sdk -key uid -value "1490148116536" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key hwid -value "1489991901929" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key bspid -value "1490148111851" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1490148116536"
webtalk_add_data -client sdk -key uid -value "1490148178619" -context "sdk\\\\bsp/1490148178619"
webtalk_add_data -client sdk -key hwid -value "1489991901929" -context "sdk\\\\bsp/1490148178619"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1490148178619"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1490148178619"
webtalk_add_data -client sdk -key uid -value "1490148181470" -context "sdk\\\\application/1490148181470"
webtalk_add_data -client sdk -key hwid -value "1489991901929" -context "sdk\\\\application/1490148181470"
webtalk_add_data -client sdk -key bspid -value "1490148178619" -context "sdk\\\\application/1490148181470"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1490148181470"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1490148181470"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1490148181470"
webtalk_transmit -clientid 2584342861 -regid "211278044_0_0_104" -xml C:\\Users\\Wangsir\\Documents\\SOC\\xup\\lab6SoC\\lab6SoC.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Wangsir\\Documents\\SOC\\xup\\lab6SoC\\lab6SoC.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Wangsir\\Documents\\SOC\\xup\\lab6SoC\\lab6SoC.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
